server:
  port: 8080

spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: msvc-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: monopatin
          uri: 'http://localhost:9090'
          predicates:
            - Path=/api/monopatin/**
        - id: viaje
          uri: 'http://localhost:9090'
          predicates:
            - Path=/api/viaje/**
        - id: tarifa
          uri: 'http://localhost:9090'
          predicates:
            - Path=/api/tarifa/**
        - id: administracion
          uri: 'http://localhost:9080'
          predicates:
            - Path=/api/admin/**
        - id: mantenimiento
          uri: 'http://localhost:8060'
          predicates:
            - Path=/api/mantenimiento/**
        - id: cliente
          uri: 'http://localhost:5080'
          predicates:
            - Path=/api/cliente/**
        - id: auth_user
          uri: 'http://localhost:8070'
          predicates:
            - Path=/api/auth/**
eureka:
  client:
    register-with-eureka: false