server:
  port: 8060

spring:
  application:
    name: msvc-mantenimiento
  data:
    mongodb:
      authentication-database: admin
      uri: mongodb://root:root@localhost:27017/mantenimientos?authSource=admin

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka